---
  
  - name: Update repository
    shell: 'apt-get update --fix-missing'

  - name: add GPG key
    command: 'apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D'


  - name: verify APT is pulling from right cache
    shell: 'apt-cache policy docker-engine'


  - name: install dependancy apparmor
    apt: name=apparmor state=present

  - name: install docker
    apt: name=docker.io state=latest
    notify: test docker


